
exports.seed = async function(knex) {
// Inserts seed entries
  await knex('instructions').insert([
    {id: 1, step: 1, time: '5 min', directions: 'Break up pork rinds so theyre in smaller pieces that are able to get coated properly'},
    {id: 2, step: 2, time: '10 min', directions: 'Put your pan on medium heat and add 2 Tbsp. Butter. Let this cook down until it becomes browned'},
    {id: 3, step: 3, time: '5 min', directions: 'Remove from heat and add heavy cream and erythritol. Start mixing it and return to the heat'},
    {id: 4, step: 4, time: '5 min', directions: 'The caramel mixture will start bubbling. Continue mixing it until the color you want is attained'},
    {id: 5, step: 5, time: '2 min', directions: 'Once the caramel comes together, add your pork rinds and mix them in. Make sure all pork rinds get coated'},
    {id: 6, step: 6, time: '45 min', directions: 'Transfer pork rinds to a container or onto foil and put in the fridge for 20-45 minutes'},
    {id: 7, step: 7, time: '3 min', directions: 'Serve with milk and garnish with nuts if youd like'},
    {id: 8, step: 1, time: '60 minutes', directions:'Chill pie crust for 30-60 minutes in the fridge to firm up prior to rolling out'},
    {id: 9, step: 2, time: '30 minutes', directions:'Preheat oven to 375 degrees F'},
    {id: 10, step: 3, time: '10 minutes', directions:'Roll the chilled pie crust between two sheets of parchment paper and transfer to your pie/tart pan. Form the crust to the sides of the pan and remove any excess'},
    {id: 11, step: 4, time: '2 minutes', directions:'Line the inside of the pie crust with a square of parchment paper and fill to the edges with pie weights or use another oven safe pan/pot (as shown in video) to prevent crust from inflating'},
    {id: 12, step: 5, time: '15 minutes', directions:'Bake the crust for about 15 minutes, until pale golden. Remove from the oven and allow to cool. Reduce oven temp to 350 degrees F'},
    {id: 13, step: 6, time: '5 minutes', directions:'Combine the eggs, heavy cream, salt, and pepper in a large bowl. Using a hand mixer, blend until well combined'},
    {id: 14, step: 7, time: '5 minutes', directions:'Layer the bacon and cheese in the bottom of the pie crust, then pour the egg mixture on top'},
    {id: 15, step: 8, time: '45 minutes', directions:'Cover the edges with foil or a pie crust shield if they are very exposed, then bake for 40-45 minutes, or until a knife inserted 2 inches from the edge comes out clean'},
    {id: 16, step: 9, time: '10 minutes', directions:'The center will be set but still slightly jiggly. Allow to cool for 10 minutes before cutting and serving'},
    {id: 17, step: 1, time: '10 minutes', directions:'Gather and prep all ingredients'},
    {id: 18, step: 2, time: '2 minutes', directions:'In a bowl, combine greek yogurt, fresh mint, fresh garlic, olive oil, and salt and pepper. Stir until combined well and set aside'},
    {id: 19, step: 3, time: '5 minutes', directions:'Put the halloumi cheese into a nonstick frying pan without oil or butter. Fry on medium heat for 2-4 minutes. Apply pressure to the middle of the cheese before flipping to ensure the middle of the cheese is getting cooked'},
    {id: 20, step: 4, time: '5 minutes', directions:'Flip the halloumi cheese over and do the same to this side until the cheese is golden brown in color. Remove from the frying pan carefully'},
    {id: 21, step: 5, time: '1 minute', directions:'Put mixed greens into a serving bowl and add the halloumi cheese on top. Squeeze the lemon on top and serve with the mint dressing'},
    {id: 22, step: 1, time: '10 minutes', directions:'Prep and measure all ingredients out for ease of use'},
    {id: 23, step: 2, time: '1 minute', directions:'Line a cupcake tray with parchment paper liners. Alternatively, you can use silicone cupcake molds'},
    {id: 24, step: 3, time: '1 minute', directions:'Add the butter, powdered stevia/erythritol blend (you can powder it using a small blender or coffee grinder), peanut butter, and vanilla extract to a pan'},
    {id: 25, step: 4, time: '5 minutes', directions:'Heat the mixture over medium-low heat, stirring occasionally, until the mixture is smooth and has no lumps'},
    {id: 26, step: 5, time: '10 minutes', directions:'Evenly distribute the peanut butter mixture between the cupcake tray liners'},
    {id: 27, step: 6, time: '5 minutes', directions:'In a microwave-safe container, melt the chocolate in the microwave in 30-second intervals until smooth and glossy'},
    {id: 28, step: 7, time: '5 minutes', directions:'Evenly distribute a thin chocolate layer to the top of each peanut butter layer'},
    {id: 29, step: 8, time: '30 minutes', directions:'Place the cupcake tray into the refrigerator for 30 minutes or until set completely. Will last a week stored in an airtight container'},
    {id: 30, step: 1, time: '2 minute', directions:'In a microwave-safe bowl, place your mozzarella cheese. Add the oregano, paprika, red chili flakes, and pepper'},
    {id: 31, step: 2, time: '2 minutes', directions:'Heat the cheese up in the microwave, for approximately one minute, or until it has melted'},
    {id: 32, step: 3, time: '5 minutes', directions:'Stir your almond flour into the cheese, mixing until a dough has been formed'},
    {id: 33, step: 4, time: '5 minutes', directions:'Place your dough onto a piece of parchment paper and a pizza tray if you have one. Although, it’s not necessary, it’s just for stabilization when transferring to the oven.Using your hands, knead the dough together'},
    {id: 34, step: 5, time: '5 minutes', directions:'Using a rolling pin, roll the dough into a circle shape. Roll the edges of the dough 2 inches towards the center of the pizza to make a crust'},
    {id: 35, step: 6, time: '2 minutes', directions:'Place a dollop of tomato paste onto the dough, spreading it around with a spoon'},
    {id: 36, step: 7, time: '2 minutes', directions:'Using a teaspoon, place ½ chunks of cream cheese around the pizza. Top with jalapenos, bacon, chives and garlic powder'},
    {id: 37, step: 8, time: '45 minutes', directions:'Cook at 350°F for 30-40 minutes'},
  ]);
};
