
exports.seed = async function(knex) {
// Inserts seed entries
  await knex('ingredients').insert([
    {id: 1, ingredient: 'Heavy Cream', quantity: '2 Tbsp'},
    {id: 2, ingredient: 'Pork Rinds', quantity: '1 oz'},
    {id: 3, ingredient: 'Coconut Milk', quantity: '1 cup'},
    {id: 4, ingredient: 'Butter', quantity: '2 Tbsp'},
    {id: 5, ingredient: 'Ground Cinnamon', quantity: '1/4 Tbsp'},
    {id: 6, ingredient: 'Erythritol', quantity: '1 Tbsp'},
    {id: 7, ingredient: 'Heavy Cream', quantity: '1 cup'},
    {id: 8, ingredient: 'eggs', quantity: '4'},
    {id: 9, ingredient: 'pink salt', quantity: '1/2 tsp'},
    {id: 10, ingredient: 'black pepper', quantity: '1/4 tsp'},
    {id: 11, ingredient: 'toppings', quantity: '8 ounces'},
    {id: 12, ingredient: 'cheese', quantity: '1 cup'},
    {id: 13, ingredient: 'Haloumi Cheese', quantity: '10 ounces'},
    {id: 14, ingredient: 'Greek Yogurt', quantity: '1 cup'},
    {id: 15, ingredient: 'Chopped Mint', quantity: '1/4 cup'},
    {id: 16, ingredient: 'Olive Oil', quantity: '2 Tbsp'},
    {id: 17, ingredient: 'Garlic', quantity: '1 Tsp'},
    {id: 18, ingredient: 'Salt and Pepper', quantity: 'preference'},
    {id: 19, ingredient: 'Mixed Greens', quantity: '10 ounces'},
    {id: 20, ingredient: 'Lemon', quantity: '1'},
    {id: 21, ingredient: 'Butter', quantity: '1/4 cup'},
    {id: 22, ingredient: 'Powdered Stevia/Erythritol Blend', quantity: '1/3 cup'},
    {id: 23, ingredient: 'Peanut Butter', quantity: '1/2 cup'},
    {id: 24, ingredient: 'Vanilla Extract', quantity: '1/2 Tsp'},
    {id: 25, ingredient: 'Low Carb Chocolate Milk', quantity: '4 ounces'},
    {id: 26, ingredient: 'Shredded Mozzarella Cheese', quantity: '2 cups'},
    {id: 27, ingredient: 'Almond Flour', quantity: '3/4 cups'},
    {id: 28, ingredient: 'Oregano', quantity: '1/2 Tsp'},
    {id: 29, ingredient: 'Paprika', quantity: '1/2 Tsp'},
    {id: 30, ingredient: 'Red Chili Flakes', quantity: '1/2 Tsp'},
    {id: 31, ingredient: 'Pepper', quantity: '1/2 Tsp'},
    {id: 32, ingredient: 'Tomato Paste', quantity: '1 Tbsp'},
    {id: 33, ingredient: 'Bacon Bits', quantity: '1/3 cup'},
    {id: 34, ingredient: 'Chopped Jalapenos', quantity: '1/3 cup'},
    {id: 35, ingredient: 'Cream Cheese', quantity: '11 Tsp'},
    {id: 36, ingredient: 'Garlic Powder', quantity: '1/2 Tsp'},
    {id: 37, ingredient: 'Chopped Olives', quantity: '3 Tbsp'},
  ]);
};
